import glob, os
from os.path import expanduser

from .desktop import Desktop

def refresh_apps(just_delete = False):
    desktop_prefix = "flatpak-runner-autogen-"
    home = expanduser("~")
    target_folder = os.path.join(home, ".local/share/applications")
    src_folders = [ os.path.join(home, ".local/share/flatpak/exports/share/applications") ]
    
    # remove all autogenerated entries first
    for i in glob.glob(os.path.join(target_folder, desktop_prefix + "*")):
        os.remove(i)

    if just_delete:
        return []

    apps = []
    
    # scan provided desktop files
    for D in src_folders:
        for i in glob.glob(os.path.join(D, "*.desktop")):
            d = Desktop(i)
            if not d.is_app: continue
            fpk = d.app
            tfile = os.path.join(target_folder, desktop_prefix + fpk + ".desktop")
            if os.path.exists(tfile): continue
            d.save_processed(tfile)
            apps.append( dict(name = fpk,
                              icon = d.icon) )
    return apps
