#!/bin/sh -e

LIBS="libEGL.so.1
      libEGL.so.1.0.0
      libGLESv2.so.2
      libGLESv2.so.2.0.0
      libOpenCL.so.1
      libOpenCL.so.1.0.0
      libandroid-properties.so.1
      libandroid-properties.so.1.0.0
      libgralloc.so
      libgralloc.so.1
      libgralloc.so.1.0.0
      libhardware.so.2
      libhardware.so.2.0.0
      libhwc2.so
      libhwc2.so.1
      libhwc2.so.1.0.0
      libhybris
      libhybris-common.so.1
      libhybris-common.so.1.0.0
      libhybris-eglplatformcommon.so.1
      libhybris-eglplatformcommon.so.1.0.0
      libhybris-hwcomposerwindow.so.1
      libhybris-hwcomposerwindow.so.1.0.0
      libnfc_ndef_nxp.so.1
      libnfc_ndef_nxp.so.1.0.0
      libnfc_nxp.so.1
      libnfc_nxp.so.1.0.0
      libsync.so.2
      libsync.so.2.0.0
      libvibrator.so.1
      libvibrator.so.1.0.0
      libwayland-egl.so.1
      libwayland-egl.so.1.0.0
      libwifi.so.1
      libwifi.so.1.0.0"

TARGET="$HOME/.local/share/flatpak/extension/org.freedesktop.Platform.GL.host/aarch64/1.4"
LIBDIR="/usr/lib64"

mkdir -p $TARGET/lib64/libhybris

echo "Synchronize main libraries"
for file in ${LIBS}; do
    if [ -f ${LIBDIR}/$file ]; then
        echo "  $file"
        #ln -s /var/run/host/${LIBDIR}/${file} ${TARGET}/lib64/${file}
        #rm ${TARGET}/lib64/${file} || true
        rsync -a ${LIBDIR}/${file} ${TARGET}/lib64/${file} || echo "Couldn't copy, probably not found:" ${LIBDIR}/${file}
    fi
done
echo

echo "Synchronize /usr/lib64/libhybris"
rsync -av --delete /usr/lib64/libhybris/ $TARGET/lib64/libhybris/
echo

mkdir -p $TARGET/libexec/droid-hybris
echo "Synchronize /usr/libexec/droid-hybris"
rsync -av --delete /usr/libexec/droid-hybris/ $TARGET/libexec/droid-hybris/
echo
