#!/usr/bin/python3

import glob, os
from os.path import expanduser

desktop_prefix = "flatpak-runner-autogen-"
home = expanduser("~")
target_folder = os.path.join(home, ".local/share/applications")
src_folders = [ os.path.join(home, ".local/share/flatpak/exports/share/applications") ]


# get key from loaded ini file
def get_key(key, d):
    for l in d:
        s = l.split("=", 1)
        if len(s) > 1 and s[0].strip()==key:
            return s[1]
    return None

# replace ini key value
def replace_key(key, val, d):
    for i in range(len(d)):
        s = d[i].split("=", 1)
        if len(s) > 1 and s[0].strip() == key:
            d[i] = key + "=" + val
    return d

# helper function for loading and adjusting desktop file
def scan_desktop(fname):
    with open(fname, 'r') as f:
        d = [l.strip() for l in f]
    fpk = get_key('X-Flatpak', d)
    if fpk is None:
        return None, None
    nexe = "/usr/bin/flatpak-runner " + fpk
    d = replace_key("Exec", nexe, d)
    d = replace_key("Icon", "flatpak-runner", d)
    return fpk, '\n'.join(d)

# remove all autogenerated entries first
for i in glob.glob(os.path.join(target_folder, desktop_prefix + "*")):
    os.remove(i)

# scan provided desktop files
for D in src_folders:
    for d in glob.glob(os.path.join(D, "*.desktop")):
        fpk, s = scan_desktop(d)
        if fpk is None: continue
        tfile = os.path.join(target_folder, desktop_prefix + fpk + ".desktop")
        if os.path.exists(tfile): continue
        with open(tfile, 'w') as f:
            f.write(s)
